config/routes.rb
Rails.application.routes.draw do
  root 'offers#index'
  resources :offers, only: :index
end

app/models/offer.rb
# Offer class is to get offers from fyber API.
# It includes HTTParty to interact HTTP URL.
class Offer
  include HTTParty
  base_uri 'http://api.fyber.com/feed/v1/offers.json'
  format :json
  attr_reader :response

  def initialize(params)
    @uid = params[:uid]
    @pub0 = params[:pub0]
    @page = params[:page]
  end

  def hashkey
    query_string = parameters.map { |k, v| "#{k}=#{v}&" }.sort.join
    digest(query_string)
  end

  def fetch
    @response = self.class.get('/', query: parameters_with_hashkey)
    fail 'InvalidSignatureError' unless valid?
    @response
  end

  def valid?
    response.headers['X-Sponsorpay-Response-Signature'] == digest(response.body)
  end

  def parameters_with_hashkey
    parameters.merge(hashkey: hashkey)
  end

  def parameters
    @parameters = {
      uid: @uid,
      pub0: @pub0,
      page: @page,
      appid: appid,
      ip: ip,
      locale: locale,
      device_id: device_id,
      timestamp: Time.now.to_i
    }
  end

  private

  def digest(string)
    Digest::SHA1.hexdigest(string + api_key)
  end

  def api_key
    Rails.application.secrets.fyber['api_key']
  end

  def appid
    Rails.application.secrets.fyber['appid']
  end

  def ip
    Rails.application.secrets.fyber['ip']
  end

  def locale
    Rails.application.secrets.fyber['locale']
  end

  def device_id
    Rails.application.secrets.fyber['device_id']
  end
end

app/controllers/application_controller.rb
# Application controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
# Serve Offers requests
class OffersController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.js do
        offer = Offer.new(offer_params)
        @offers = JSON.parse(offer.fetch.body)['offers']
      end
    end
  end

  private

  def offer_params
    params[:offer].permit(:uid, :pub0, :page) if params[:offer]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FyberOffer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offers/_search_result.html.slim
- if offers
  - offers.each do |offer|
    .offer
      .title = offer['title']
      .payout = offer['payout']
      .thumbnail = image_tag offer['thumbnail']['lowres']

app/views/offers/index.html.slim
h1 Offers
= form_tag(offers_path, method: 'get', remote: true) do
  #div
    = label_tag 'uid', 'UID'
    = text_field_tag 'offer[uid]'
  #div
    = label_tag 'pub0', 'Pub0'
    = text_field_tag 'offer[pub0]'
  #div
    = label_tag 'page', 'Page'
    = text_field_tag 'offer[page]'
  #div
    = button_tag 'Search'

h2 Search Result
#search-result
  = render 'search_result', offers: @offers

app/views/offers/index.js.erb
<% if @offers && @offers.any? %>
  $('#search-result').html('<%= j render 'search_result', offers: @offers %>');
<% else %>
  $('#search-result').html('No offers available')
<% end %>